services:
   - type: web
     name: multiservicios-backend
     env: node
     plan: free
     buildcommand: npm install
     startcommand: npx json-server db.json --port 10000 --host 0.0.0.0
     healthCheckPath: /users
     autoDeploy: true
